// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: register.proto

#include "register.pb.h"
#include "register.grpc.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/channel_interface.h>
#include <grpcpp/impl/codegen/client_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/rpc_service_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/sync_stream.h>
namespace Register {

static const char* RegisterService_method_names[] = {
  "/Register.RegisterService/Register",
};

std::unique_ptr< RegisterService::Stub> RegisterService::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< RegisterService::Stub> stub(new RegisterService::Stub(channel, options));
  return stub;
}

RegisterService::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_Register_(RegisterService_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status RegisterService::Stub::Register(::grpc::ClientContext* context, const ::Register::RegisterRequest& request, ::Register::RegisterResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::Register::RegisterRequest, ::Register::RegisterResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_Register_, context, request, response);
}

void RegisterService::Stub::async::Register(::grpc::ClientContext* context, const ::Register::RegisterRequest* request, ::Register::RegisterResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::Register::RegisterRequest, ::Register::RegisterResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Register_, context, request, response, std::move(f));
}

void RegisterService::Stub::async::Register(::grpc::ClientContext* context, const ::Register::RegisterRequest* request, ::Register::RegisterResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Register_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::Register::RegisterResponse>* RegisterService::Stub::PrepareAsyncRegisterRaw(::grpc::ClientContext* context, const ::Register::RegisterRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::Register::RegisterResponse, ::Register::RegisterRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_Register_, context, request);
}

::grpc::ClientAsyncResponseReader< ::Register::RegisterResponse>* RegisterService::Stub::AsyncRegisterRaw(::grpc::ClientContext* context, const ::Register::RegisterRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncRegisterRaw(context, request, cq);
  result->StartCall();
  return result;
}

RegisterService::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      RegisterService_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< RegisterService::Service, ::Register::RegisterRequest, ::Register::RegisterResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](RegisterService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::Register::RegisterRequest* req,
             ::Register::RegisterResponse* resp) {
               return service->Register(ctx, req, resp);
             }, this)));
}

RegisterService::Service::~Service() {
}

::grpc::Status RegisterService::Service::Register(::grpc::ServerContext* context, const ::Register::RegisterRequest* request, ::Register::RegisterResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace Register

