// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: echo.proto

#include "echo.pb.h"
#include "echo.grpc.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/channel_interface.h>
#include <grpcpp/impl/codegen/client_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/rpc_service_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/sync_stream.h>
namespace echo {

static const char* Echo_method_names[] = {
  "/echo.Echo/UnaryEcho",
  "/echo.Echo/UnaryLock",
};

std::unique_ptr< Echo::Stub> Echo::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< Echo::Stub> stub(new Echo::Stub(channel, options));
  return stub;
}

Echo::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_UnaryEcho_(Echo_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_UnaryLock_(Echo_method_names[1], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status Echo::Stub::UnaryEcho(::grpc::ClientContext* context, const ::echo::EchoRequest& request, ::echo::EchoResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::echo::EchoRequest, ::echo::EchoResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_UnaryEcho_, context, request, response);
}

void Echo::Stub::async::UnaryEcho(::grpc::ClientContext* context, const ::echo::EchoRequest* request, ::echo::EchoResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::echo::EchoRequest, ::echo::EchoResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_UnaryEcho_, context, request, response, std::move(f));
}

void Echo::Stub::async::UnaryEcho(::grpc::ClientContext* context, const ::echo::EchoRequest* request, ::echo::EchoResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_UnaryEcho_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::echo::EchoResponse>* Echo::Stub::PrepareAsyncUnaryEchoRaw(::grpc::ClientContext* context, const ::echo::EchoRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::echo::EchoResponse, ::echo::EchoRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_UnaryEcho_, context, request);
}

::grpc::ClientAsyncResponseReader< ::echo::EchoResponse>* Echo::Stub::AsyncUnaryEchoRaw(::grpc::ClientContext* context, const ::echo::EchoRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncUnaryEchoRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status Echo::Stub::UnaryLock(::grpc::ClientContext* context, const ::echo::EchoRequest& request, ::echo::EchoLockResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::echo::EchoRequest, ::echo::EchoLockResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_UnaryLock_, context, request, response);
}

void Echo::Stub::async::UnaryLock(::grpc::ClientContext* context, const ::echo::EchoRequest* request, ::echo::EchoLockResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::echo::EchoRequest, ::echo::EchoLockResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_UnaryLock_, context, request, response, std::move(f));
}

void Echo::Stub::async::UnaryLock(::grpc::ClientContext* context, const ::echo::EchoRequest* request, ::echo::EchoLockResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_UnaryLock_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::echo::EchoLockResponse>* Echo::Stub::PrepareAsyncUnaryLockRaw(::grpc::ClientContext* context, const ::echo::EchoRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::echo::EchoLockResponse, ::echo::EchoRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_UnaryLock_, context, request);
}

::grpc::ClientAsyncResponseReader< ::echo::EchoLockResponse>* Echo::Stub::AsyncUnaryLockRaw(::grpc::ClientContext* context, const ::echo::EchoRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncUnaryLockRaw(context, request, cq);
  result->StartCall();
  return result;
}

Echo::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      Echo_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< Echo::Service, ::echo::EchoRequest, ::echo::EchoResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](Echo::Service* service,
             ::grpc::ServerContext* ctx,
             const ::echo::EchoRequest* req,
             ::echo::EchoResponse* resp) {
               return service->UnaryEcho(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      Echo_method_names[1],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< Echo::Service, ::echo::EchoRequest, ::echo::EchoLockResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](Echo::Service* service,
             ::grpc::ServerContext* ctx,
             const ::echo::EchoRequest* req,
             ::echo::EchoLockResponse* resp) {
               return service->UnaryLock(ctx, req, resp);
             }, this)));
}

Echo::Service::~Service() {
}

::grpc::Status Echo::Service::UnaryEcho(::grpc::ServerContext* context, const ::echo::EchoRequest* request, ::echo::EchoResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status Echo::Service::UnaryLock(::grpc::ServerContext* context, const ::echo::EchoRequest* request, ::echo::EchoLockResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace echo

